### PR TITLE
Updating Drupal 7 vhost to match new .htaccess in latest version of c…

### PR DESCRIPTION
**Pull request by dzink**
…ore.

### CODE REVIEW

**Comment by tizzo** [comment]
We should probably also have an issue to update  the 8 vhost template too?

**Comment by lliss** [comment]
Actually, I'd just make a singe PR to update all the Vhost templates. But what you have looks right.

**Comment by dzink** [comment]
@tizzo @lliss I've grabbed the relevant lines from the appropriate branch at https://github.com/drupal/drupal/

**Comment by dzink** [comment]
Rebased on fix-tests to confirm that this works.

**Comment by lliss** [comment]
Superseded by https://github.com/tizzo/fetcher/pull/15

**Pull request closed without merging**
